services:
  langtool:
    image: python:3-alpine
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - .:/srv
    working_dir: /srv
    command: python -m http.server 8000 --bind 0.0.0.0